### PR TITLE
chore: speed up the dev deployment test in gh actions

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Comment by openoms** [comment]
LND still timed out in the first run, but faster on the second run:
```
module.bitcoin.helm_release.lnd: Creation complete after 7m3s [id=lnd1]
```
vs in https://github.com/GaloyMoney/charts/actions/runs/4174578931/jobs/7228334686
```
module.bitcoin.helm_release.lnd: Creation complete after 9m53s [id=lnd1]
```

**Comment by openoms** [comment]
With increased CPU to 200m still failed first. but the second run is fast:
```
module.bitcoin.helm_release.lnd: Creation complete after 3m13s [id=lnd1]
```

**Comment by openoms** [comment]
Locally LND on regtest uses 997m RAM:
image

**Comment by openoms** [comment]
With the three things altogether there is a 3x gain here. Running the dev tests took ~45 minutes on other pending PRs, here it is 14 minutes.
lnd now deploying in under 2 minutes:
```
module.bitcoin.helm_release.lnd: Creation complete after 1m17s [id=lnd1]
```
using the pregenerated wallet reduced  the time for lnd to finish to roughly half in my local env from 3 minutes to similar as here.

**Comment by openoms** [comment]
local with loadWallet enabled:
```
time make redeploy-bitcoin
...
module.bitcoin.helm_release.lnd: Creation complete after 33s [id=lnd1]

Apply complete! Resources: 9 added, 4 changed, 1 destroyed.

real    1m42.527s
user    0m15.001s
sys     0m1.671s
```

local test with loadWallet disabled:
```
time make redeploy-bitcoin
...
module.bitcoin.helm_release.lnd: Creation complete after 43s [id=lnd1]

Apply complete! Resources: 8 added, 6 changed, 1 destroyed.

real    1m39.290s
user    0m13.423s
sys     0m1.685s
```
As using a pregenerated wallet does not make much difference will remove the option.

**Review by krtk6160 — APPROVED** [review]

**Pull request merged**
