### PR TITLE
chore: add oathkeeper_api and kratos_public smoketests

### PR DESCRIPTION
**Pull request by openoms**

### CODE REVIEW

**Review by krtk6160 — APPROVED** [review]
Should be rebased once #2492 is merged. It should fix the admin panel smoketest.

**Comment by openoms** [comment]
Interesting error in https://github.com/GaloyMoney/charts/actions/runs/4072118841/jobs/7014893997 :
```
module.galoy.helm_release.galoy: Still creating... [10s elapsed]
╷
│ Warning: Helm release "galoy" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.galoy.helm_release.galoy,
│   on galoy/main.tf line 259, in resource "helm_release" "galoy":
│  259: resource "helm_release" "galoy" {
│ 
╵
╷
│ Error: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: 
│ -------------------------------------------------------------------------------
│ Error: exit status 1
│ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:146
│ nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:146
│ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:147
│ nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:147
│ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx/nginx-cfg3830810120:148
│ nginx: [warn] the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx/nginx-cfg3830810120:148
│ 2023/02/02 08:17:58 [warn] 312#312: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
│ nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
│ 2023/02/02 08:17:58 [warn] 312#312: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
│ nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
│ 2023/02/02 08:17:58 [emerg] 312#312: duplicate location "/" in /tmp/nginx/nginx-cfg3830810120:737
│ nginx: [emerg] duplicate location "/" in /tmp/nginx/nginx-cfg3830810120:737
│ nginx: configuration file /tmp/nginx/nginx-cfg3830810120 test failed
│ 
│ -------------------------------------------------------------------------------
│ 
│ 
│   with module.galoy.helm_release.galoy,
│   on galoy/main.tf line 259, in resource "helm_release" "galoy":
│  259: resource "helm_release" "galoy" {
│ 
╵
make: *** [Makefile:28: deploy] Error 1
Error: Final attempt failed. Child_process exited with error code 2
```

**Comment by krtk6160** [comment]
> Interesting error in https://github.com/GaloyMoney/charts/actions/runs/4072118841/jobs/7014893997 :
> 
> ```
> module.galoy.helm_release.galoy: Still creating... [10s elapsed]
> ╷
> │ Warning: Helm release "galoy" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
> │ 
> │   with module.galoy.helm_release.galoy,
> │   on galoy/main.tf line 259, in resource "helm_release" "galoy":
> │  259: resource "helm_release" "galoy" {
> │ 
> ╵
> ╷
> │ Error: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: 
> │ -------------------------------------------------------------------------------
> │ Error: exit status 1
> │ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:146
> │ nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:146
> │ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:147
> │ nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx/nginx-cfg3830810120:147
> │ 2023/02/02 08:17:58 [warn] 312#312: the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx/nginx-cfg3830810120:148
> │ nginx: [warn] the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx/nginx-cfg3830810120:148
> │ 2023/02/02 08:17:58 [warn] 312#312: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
> │ nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
> │ 2023/02/02 08:17:58 [warn] 312#312: could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
> │ nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
> │ 2023/02/02 08:17:58 [emerg] 312#312: duplicate location "/" in /tmp/nginx/nginx-cfg3830810120:737
> │ nginx: [emerg] duplicate location "/" in /tmp/nginx/nginx-cfg3830810120:737
> │ nginx: configuration file /tmp/nginx/nginx-cfg3830810120 test failed
> │ 
> │ -------------------------------------------------------------------------------
> │ 
> │ 
> │   with module.galoy.helm_release.galoy,
> │   on galoy/main.tf line 259, in resource "helm_release" "galoy":
> │  259: resource "helm_release" "galoy" {
> │ 
> ╵
> make: *** [Makefile:28: deploy] Error 1
> Error: Final attempt failed. Child_process exited with error code 2
> ```

Will try to debug locally

**Comment by openoms** [comment]
Couldn't reproduce the erro locally, but might be related to this: https://github.com/GaloyMoney/charts/pull/2497

**Comment by openoms** [comment]
Rebased after ingress-nginx is downgraded.

**Review by krtk6160 — APPROVED** [review]

**Pull request merged**
